version: "3"
services:
  nginx:
    restart: always
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./src/:/var/www/html
  php:
    restart: always
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    environment:
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    volumes:
      - ./src/:/var/www/html
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  internal:
    driver: bridge