version: '3.3'
volumes:
  data:
services:
  mysqlDb:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=app_development
  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysqldb
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1