version: "3.8"

services:
  postgres:
    container_name: postgresql
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      {
        DATABASE_HOST=127.0.0.1,
        POSTGRES_USER=postgres,
        POSTGRES_PASSWORD=postgres,
        POSTGRES_DB=postgres,
        POSTGRES_HOST_AUTH_METHOD=trust
      }

  pgadmin:
    container_name: pgadmin4
    restart: always
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres
